### PR TITLE
Change the way we calculate attempts

### PR DESCRIPTION
**Pull request by yoshuawuyts**
This PR changes the way we interpret "retries". Before this PR "3 retries" meant: "1 try, and 3 additional attempts before we give up". That felt a bit counter-intuitive, so instead this PR changes the meaning of "3 retries" to mean: "3 tries in total".

Filing this because #15 is a breaking change anyway, so I figured we might as well tidy this up too. As a consequence `Backoff::next` has been removed in favor of just working with the iterators directly instead, which I think makes a little more sense.

@demoray can I ask you to take a look at this? I've changed the counting logic here to count down instead of rounding up. I think that's easier for our purposes, but I'm also a little sleepy so some extra eyes would be helpful here.

### CODE REVIEW

**Comment by demoray** [comment]
yep, looking now.

**Comment by demoray** [comment]
I don't think this works as expected.  Since we are now counting down on the retry count, the factor of work gets smaller each time, not larger.

```
        self.retry_count -= 1;
        ...
        // Create exponential duration.
        let exponent = self.inner.factor.saturating_pow(self.retry_count);
        let duration = self.inner.min.saturating_mul(exponent);
```

**Comment by demoray** [comment]
Also, by changing the model from "N retries" (up to N+1 total tries) to "up to N tries", perhaps rename everything that uses "retry" to "try" or "attempt" such that the language matches the intent.

**Comment by demoray** [comment]
I verified this doesn't work as expected by inserting the following line into the next function.

`println!("duration {duration:?} exponent: {exponent:?}");`

The exponent goes down, which reduces the duration increase during successive iterations.

**Comment by yoshuawuyts** [comment]
Alright, I think this should work as expected now!

**Pull request merged**
